# Generated by Django 5.2.1 on 2025-12-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todolist',
        ),
    ]
