# Generated by Django 5.2.1 on 2025-12-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
